// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace WinEF.Entities;

public partial class Course
{
    [Key]
    public int CourseNumper { get; set; }

    [Required]
    [StringLength(50)]
    public string Name { get; set; }

    public int Duration { get; set; }

    [ForeignKey("TrainingCoursesCourseNumper")]
    [InverseProperty("TrainingCoursesCourseNumpers")]
    public virtual ICollection<Employee> Employees { get; set; } = new List<Employee>();
}