// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace WinEF.Entities;

public partial class Department
{
    [Key]
    public int DepartmentID { get; set; }

    public string Name { get; set; }

    [InverseProperty("DepartmentsDepartment")]
    public virtual ICollection<Employee> Employees { get; set; } = new List<Employee>();
}