// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace WinEF.Entities;

[Index("DepartmentsDepartmentID", Name = "IX_Employees_DepartmentsDepartmentID")]
public partial class Employee
{
    [Key]
    public int ID { get; set; }

    public string Name { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal Salary { get; set; }

    public int? DepartmentsDepartmentID { get; set; }

    public string Adderess { get; set; }

    [ForeignKey("DepartmentsDepartmentID")]
    [InverseProperty("Employees")]
    public virtual Department DepartmentsDepartment { get; set; }

    [ForeignKey("EmployeesID")]
    [InverseProperty("Employees")]
    public virtual ICollection<Course> TrainingCoursesCourseNumpers { get; set; } = new List<Course>();
}